### ISSUE TITLE
Custom Class Names

### ISSUE THREAD

**Issue by beinginharmony** [stubbornella/oocss#95] opened 2011-09-14 19:26 UTC
Hi, using frequently applied class names like "page" or unique ID's like "content" might not be the best idea since various CMS's and their modules, plugins also use this type of naming.

Perhaps you could add the prefix "oocss_" to these more common naming conventions so "page" becomes "oocss_page"? I am not sure whether you use #content or not or what other common names might appear, but ideally they should all have an unique prefix.

**Comment by neonstalwart** [comment] 2011-09-14 20:18
duplicate of #17

**Closed as completed** 2011-09-14 21:01 UTC
