### ISSUE TITLE
"extends:.page" in template.css

### ISSUE THREAD

**Issue by JimmyVolatile** [stubbornella/oocss#2] opened 2009-06-29 08:03 UTC
Hi, all.

I'm very curious about this code in template.css:
".liquid{extends:.page; width: auto;margin:0;}"

Especially, I'm wondering about the "extends:.page;" part. I've never heard about this rule. Has it got support in newer browsers?

Kind regards, Jimmy Volatile

**Comment by stubbornella** [comment] 2009-07-02 00:19
Nope, that's something I'm working on which will eventually have support either via browser vendors/w3c or preprocessing.

**Comment by JimmyVolatile** [comment] 2009-07-02 07:13
Ok. Thanks for quenching my curiosity.

IMHO this is certainly worth mentioning in your FAQ to prevent any confusion. Or, at least as a comment in the CSS-file right after the selector containing the extends-rule. Maybe: "/\* 'extends:' is a possible future CSS feature */" or something of a similar meaning.

Do you have a draft or suggestion for its rule definition the same way W3C has?

/Jimmy

**Comment by anthonyshort** [comment] 2009-07-28 02:31
Thought I'd mention I've added this ability, using this syntax, to my CSS preprocessor - http://github.com/anthonyshort/csscaffold/tree/master

It allows one selector to take on all the properties of another selector in all instances.

**Comment by martinklepsch** [comment] 2009-10-05 21:12
@anthonyshort the rendered result would be the same but the problem is that your preprocessor creates _(x \* y - x)_ lines/rules of overhead when  
_x_ = number of lines/rules the definition has you want to include with 'extend:'  
_y_ = number how often you use 'extend:'   

to be correct you have to add _y_ rules/lines in the end because 'extend:' is one too.

**Comment by anthonyshort** [comment] 2009-10-05 23:00
The overhead is very little, as it compresses/optimizes the css at the end, so duplicate selectors, like what could be created with 'extends', would be merged. For the selectors it can't merge, gzipping should take care of the rest of the overhead.

**Comment by martinklepsch** [comment] 2009-10-06 06:57
but you dont have duplicate selectors... you have duplicate properties or? (im not quite sure how you implemented that)  
the only style of writing css that could remove duplicate properties is the **one-property-per-line** style as google uses it.

**Comment by stubbornella** [comment] 2009-11-25 19:34
@mklappstuhl I've written up how I think this should work here: http://www.slideshare.net/stubbornella/css-wish-list

@anthonyshort Ideally this would be in the browser, a significant portion of users have gzip disabled (often due to antivirus software), so relying on compression isn't enough.

In a preprocessor, extends adds a new selector string _at the same place in the code as the rule being extended_. This means you can make use of CSS built in comma delimited selector string to share rulesets. Only a small portion of the code is duplicated.

**Comment by stubbornella** [comment] 2009-11-25 19:35
Closing this as I've removed that bit of code, we can move any discussion to the google group going forward.

**Closed as completed by stubbornella** 2009-11-25 19:35 UTC
