### ISSUE TITLE
Fixed width units incorrect size, lastUnit off screen (migrated from lighthouse)

### ISSUE THREAD

**Issue by jonherman** [stubbornella/oocss#11] opened 2009-07-01 19:33 UTC
Reported by nicole (at stubbornella) | April 12th, 2009 @ 12:18 AM

I try this

image or flash
Text and other objects
But I don't get the correct width for the first div instead if I use a class like .size345px{width:345px;} I get the correct width.
image or flash
Text and other objects
With this code in IE6 I see the text inside lastUnit that has a margin- left:-3px and so it exit from screen.

**Comment by stubbornella** [comment] 2009-07-02 00:18
I must say, I never completely understood this comment, though I did want to bug track it in case someone could make it more clear what wasn't working. I'll leave it open a while longer, then close it if no one speaks up.

**Comment by stubbornella** [comment] 2009-11-25 19:46
Unable to reproduce

**Closed as completed by stubbornella** 2009-11-25 19:46 UTC
